CleanArchitecture.MVC/Controllers/BookController.cs
using AutoMapper;
using CleanArchitecture.MVC.Services.Contracts;
using CleanArchitecture.MVC.ViewModels.Book;
using Microsoft.AspNetCore.Mvc;

namespace CleanArchitecture.MVC.Controllers
{
    public class BookController : Controller
    {
        private readonly IBooksService _booksService;
        private readonly IMapper _mapper;

        public BookController(IBooksService booksService,IMapper mapper)
        {
            _booksService = booksService;
            _mapper = mapper;
        }

        #region Get List

        // GET: BooksController
        public async Task<ActionResult> Index()
        {
            //get books list
            var response = await _booksService.GetBooks();

            return View(response.Data);
        }


        #endregion

        #region Get Item

        // GET: BooksController/Details/5
        public async Task<ActionResult> Details(int id)
        { 
            //get book info
            var response = await _booksService.GetBook(id);

            return View(response.Data);
        }

        #endregion

        #region Create

        // GET: BooksController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: BooksController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateBookViewModel bookViewModel)
        {
            try
            {
                //create book 
                var response = await _booksService.CreateBook(bookViewModel);

                if (response.IsSuccess)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    foreach (var error in response.ValidationErrors)
                    {
                        ModelState.AddModelError("", error);
                    }
                }
                
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("",ex.Message);
            }

            return View(bookViewModel);
        }

        #endregion

        #region Update

        // GET: BooksController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            //get book info
            var response = await _booksService.GetBook(id);

            //Map BookViewModel To UpdateBookViewModel
            var model = _mapper.Map<UpdateBookViewModel>(response.Data);

            return View(model);
        }

        // POST: BooksController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, UpdateBookViewModel bookViewModel)
        {
            try
            {
                //update book 
                var response = await _booksService.UpdateBook(bookViewModel);

                if (response.IsSuccess)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    foreach (var error in response.ValidationErrors)
                    {
                        ModelState.AddModelError("", error);
                    }
                }

            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }

            return View(bookViewModel);
        }

        #endregion

        #region Delete

        // GET: BooksController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            //get book info
            var response = await _booksService.GetBook(id);

            //Map BookViewModel To DeleteBookViewModel
            var model = _mapper.Map<DeleteBookViewModel>(response.Data);

            return View(model);
        }

        // POST: BooksController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id,DeleteBookViewModel book)
        {
            try
            {
                book.Id = id;

                //delete book 
                var response = await _booksService.DeleteBook(book.Id);

                if (response.IsSuccess)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    foreach (var error in response.ValidationErrors)
                    {
                        ModelState.AddModelError("", error);
                    }
                }

            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }

            return View(book);
        }

        #endregion

    }
}

CleanArchitecture.MVC/Controllers/MonitorsController.cs
using Microsoft.AspNetCore.Mvc;

namespace CleanArchitecture.MVC.Controllers
{
    public class MonitorsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

CleanArchitecture.MVC/Controllers/SettingsController.cs
using Microsoft.AspNetCore.Mvc;

namespace CleanArchitecture.MVC.Controllers
{
    public class SettingsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

CleanArchitecture.MVC/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CleanArchitecture.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CleanArchitecture.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CleanArchitecture.MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        
                        
                        @if (User.Identity.IsAuthenticated)
                        {
                            //If USer Logged in so control view depend on rols
                            
                            if (User.IsInRole("Administrators"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-warning" asp-area="" asp-controller="Settings" asp-action="Index">Settings</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-success" asp-area="" asp-controller="Monitors" asp-action="Index">Monitors</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-danger" asp-area="" asp-controller="Book" asp-action="Index">Books</a>
                                </li>
                            }
                            else if (User.IsInRole("Supervisors"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-success" asp-area="" asp-controller="Monitors" asp-action="Index">Monitors</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-danger" asp-area="" asp-controller="Book" asp-action="Index">Books</a>
                                </li>
                            }
                            else if (User.IsInRole("Users"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-danger" asp-area="" asp-controller="Book" asp-action="Index">Books</a>
                                </li>
                            }
                        }
                        
                        
                    </ul>
                    
                    <partial name="_LoginPartial"/>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CleanArchitecture.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>